<?xml version="1.0"?>
<!DOCTYPE feature_key_file [
   <!ELEMENT feature_key_file (comments, feature+)>
   <!ELEMENT comments (#PCDATA)>
   <!ELEMENT feature (name, code?, description?, is_sequential, parallel_dimensions, extractor?)>
   <!ELEMENT name (#PCDATA)>
   <!ELEMENT code (#PCDATA)>
   <!ELEMENT description (#PCDATA)>
   <!ELEMENT is_sequential (#PCDATA)>
   <!ELEMENT parallel_dimensions (#PCDATA)>
   <!ELEMENT extractor (#PCDATA)>
]>

<feature_key_file>

   <comments></comments>

   <feature>
      <name>Pitched Instruments Present</name>
      <code>I-1</code>
      <description>A feature vector indicating which pitched instruments are present. Has one entry for each of the 128 General MIDI Instrument patches (0 is Acoustic Piano, 40 is Violin, etc.). Each value is set to 1 if at least one note is played using the corresponding patch, or to 0 if that patch is never used.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>128</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Unpitched Instruments Present</name>
      <code>I-2</code>
      <description>A feature vector indicating which unpitched instruments are present. Has one entry for each of the 47 MIDI Percussion Key Map instruments. Each value is set to 1 if at least one note is played using the corresponding instrument, or to 0 if that instrument is never used. It should be noted that only MIDI Channel 10 instruments 35 to 81 are included here, as they are the ones that meet the official standard (they are correspondingly indexed in this feature vector from 0 to 46, such that index 0 corresponds to Acoustic Bass Drum, index 4 corresponds to Hand Clap, etc.).</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>47</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Note Prevalence of Pitched Instruments</name>
      <code>I-3</code>
      <description>A feature vector indicating the fraction of (pitched) notes played with each of the 128 General MIDI Instrument patches (0 is Acoustic Piano, 40 is Violin, etc.). Has one entry for each of these instruments, and the value of each is set to the number of Note Ons played with the corresponding MIDI patch, divided by the total number of Note Ons in the piece.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>128</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Note Prevalence of Unpitched Instruments</name>
      <code>I-4</code>
      <description>A feature vector indicating the fraction of (unpitched) notes played with each of the 47 MIDI Percussion Key Map instruments. Has one entry for each of these 47 instruments, and the value of each is set to the number of Note Ons played with the corresponding instrument, divided by the total number of Note Ons in the piece. It should be noted that only MIDI Channel 10 instruments 35 to 81 are included here, as they are the ones that meet the official standard (they are correspondingly indexed in this feature vector from 0 to 46, such that index 0 corresponds to Acoustic Bass Drum, index 4 corresponds to Hand Clap, etc.).</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>47</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Time Prevalence of Pitched Instruments</name>
      <code>I-5</code>
      <description>A feature vector indicating the fraction of time during which (pitched) notes are being sounded by each of the 128 General MIDI Instrument patches (0 is Acoustic Piano, 40 is Violin, etc.). Has one entry for each of these instruments, and the value of each is set to to the total time in seconds in a piece during which at least one note is being sounded with the corresponding MIDI patch, divided by the total length of the piece in seconds.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>128</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

</feature_key_file>